from .quote_models import ThemedQuote

BASE_THEMED_QUOTES: dict[str, dict[str, list[ThemedQuote]]] = {
    "ru": {
        "family": [
            ThemedQuote("family", "Все счастливые семьи похожи друг на друга.", "Лев Толстой"),
            ThemedQuote("family", "Семья - один из шедевров природы.", "Джордж Сантаяна"),
            ThemedQuote("family", "Если хотите изменить мир, идите домой и любите свою семью.", "Мать Тереза"),
            ThemedQuote("family", "Единственная скала, которая не подводит, - семья.", "Ли Якокка"),
            ThemedQuote("family", "Семья - самое важное в мире.", "Принцесса Диана"),
            ThemedQuote("family", "Любовь начинается дома, и важно не то, сколько мы делаем, а сколько любви вкладываем в это действие.", "Мать Тереза"),
            ThemedQuote("family", "Во всех смыслах семья - это связь с нашим прошлым и мост в наше будущее.", "Алекс Хейли"),
            ThemedQuote("family", "Единственная опора, которая не подводит, единственный институт, который работает, - это семья.", "Ли Якокка"),
            ThemedQuote("family", "Ты не выбираешь свою семью. Они - Божий дар тебе, как и ты - дар им.", "Десмонд Туту"),
            ThemedQuote("family", "Семья - это компас, который направляет нас. Она вдохновляет на большие высоты и поддерживает, когда мы оступаемся.", "Брэд Генри"),
            ThemedQuote("family", "Семья - это настоящее богатство.", "Ричард Бах"),
            ThemedQuote("family", "Семья - один из шедевров природы.", "Джордж Сантаяна"),
        ],
        "discipline": [
            ThemedQuote("discipline", "Мы есть то, что постоянно делаем.", "Аристотель"),
            ThemedQuote("discipline", "Дисциплина - мост между целями и достижениями.", "Джим Рон"),
            ThemedQuote("discipline", "Дисциплина равна свободе.", "Джоко Виллинк"),
            ThemedQuote("discipline", "Я не боюсь того, кто тренирует 10 000 ударов однажды.", "Брюс Ли"),
            ThemedQuote("discipline", "Никто не свободен, кто не владеет собой.", "Эпиктет"),
            ThemedQuote("discipline", "Мы становимся тем, что мы постоянно делаем.", "Стивен Кови"),
            ThemedQuote("discipline", "Делать одно и то же снова и снова - это не только скука; это значит быть управляемым, а не управлять тем, что делаешь.", "Гераклит"),
            ThemedQuote("discipline", "Никто не свободен, кто не является хозяином самому себе.", "Эпиктет"),
            ThemedQuote("discipline", "Берегите свое тело. Это единственное место, где вам предстоит жить.", "Джим Рон"),
            ThemedQuote("discipline", "Дисциплина - это мост между целями и достижениями.", "Джим Рон"),
            ThemedQuote("discipline", "Работайте над собой больше, чем над своей работой.", "Джим Рон"),
            ThemedQuote("discipline", "Успех - это устойчивый прогресс к своим личным целям.", "Джим Рон"),
        ],
        "health": [
            ThemedQuote("health", "Пусть пища будет твоим лекарством.", "Гиппократ"),
            ThemedQuote("health", "Здоровье не все, но без здоровья все - ничто.", "Артур Шопенгауэр"),
            ThemedQuote("health", "У кого нет времени для здоровья, найдет время для болезни.", "Эдвард Стэнли"),
            ThemedQuote("health", "Физическая форма - первое условие счастья.", "Джозеф Пилатес"),
            ThemedQuote("health", "Величайшее богатство - здоровье.", "Вергилий"),
            ThemedQuote("health", "Берегите свое тело. Это единственное место, где вам предстоит жить.", "Джим Рон"),
            ThemedQuote("health", "Здоровье - величайший дар, довольство - величайшее богатство, верность - лучшие отношения.", "Будда"),
            ThemedQuote("health", "Ваше тело слышит все, что говорит ваш разум.", "Наоми Джадд"),
            ThemedQuote("health", "Нужно слушать свое тело, потому что оно слушает вас.", "Фил Макгроу"),
            ThemedQuote("health", "Отдыхайте, когда устали. Освежитесь и обновите себя, свое тело, разум и дух. Потом возвращайтесь к работе.", "Ральф Марстон"),
            ThemedQuote("health", "Ваше тело слышит все, что говорит ваш разум.", "Наоми Джадд"),
            ThemedQuote("health", "Нужно слушать свое тело, потому что оно слушает вас.", "Фил Макгроу"),
        ],
        "children": [
            ThemedQuote("children", "Лучший способ сделать детей хорошими - сделать их счастливыми.", "Оскар Уайльд"),
            ThemedQuote("children", "Никогда не помогайте ребенку с задачей, которую он может решить сам.", "Мария Монтессори"),
            ThemedQuote("children", "О душе общества лучше всего говорит то, как оно относится к детям.", "Нельсон Мандела"),
            ThemedQuote("children", "Молодым нужны примеры, а не критики.", "Джон Вуден"),
            ThemedQuote("children", "Величайший признак успеха для учителя... - когда можно сказать: \"Дети теперь работают так, будто меня не существует\".", "Мария Монтессори"),
            ThemedQuote("children", "Не может быть более ясного отражения души общества, чем то, как оно относится к своим детям.", "Нельсон Мандела"),
            ThemedQuote("children", "Молодым нужны примеры, а не критики.", "Джон Вуден"),
            ThemedQuote("children", "Никто не может сделать для маленьких детей того, что делают бабушки и дедушки.", "Алекс Хейли"),
            ThemedQuote("children", "Дети не пустые сосуды, которые мы наполняем; это строители человека.", "Мария Монтессори"),
            ThemedQuote("children", "Молодым нужны примеры, а не критики.", "Джон Вуден"),
        ],
        "leadership": [
            ThemedQuote("leadership", "Лидерство - это способность превращать видение в реальность.", "Уоррен Беннис"),
            ThemedQuote("leadership", "Лидер знает путь, идет этим путем и показывает путь.", "Джон Максвелл"),
            ThemedQuote("leadership", "Менеджмент - делать дела правильно, лидерство - делать правильные дела.", "Питер Друкер"),
            ThemedQuote("leadership", "Пример - не главный способ влиять на других, а единственный.", "Альберт Швейцер"),
            ThemedQuote("leadership", "Если ваши действия вдохновляют других мечтать больше, вы лидер.", "Джон Куинси Адамс"),
            ThemedQuote("leadership", "Лидеры смотрят на горизонт, а не только на прибыль.", "Уоррен Беннис"),
            ThemedQuote("leadership", "У менеджера взгляд прикован к прибыли, у лидера - к горизонту.", "Уоррен Беннис"),
            ThemedQuote("leadership", "Лидеры делают правильные вещи; менеджеры делают вещи правильно.", "Уоррен Беннис"),
            ThemedQuote("leadership", "Менеджер принимает статус-кво; лидер его оспаривает.", "Уоррен Беннис"),
            ThemedQuote("leadership", "Лидерство - это способность превращать видение в реальность.", "Уоррен Беннис"),
            ThemedQuote("leadership", "Менеджер спрашивает как и когда, лидер спрашивает что и почему.", "Уоррен Беннис"),
            ThemedQuote("leadership", "Стать лидером - значит стать самим собой.", "Уоррен Беннис"),
        ],
        "bible": [
            ThemedQuote(
                "bible",
                "Больше всего хранимого храни сердце твое, потому что из него источники жизни.",
                "Библия, Притчи 4:23",
            ),
            ThemedQuote(
                "bible",
                "Делая добро, да не унываем, ибо в свое время пожнем, если не ослабеем.",
                "Библия, Галатам 6:9",
            ),
            ThemedQuote(
                "bible",
                "Все могу в укрепляющем меня Иисусе Христе.",
                "Библия, Филиппийцам 4:13",
            ),
            ThemedQuote(
                "bible",
                "Так да светит свет ваш пред людьми, чтобы они видели ваши добрые дела и прославляли Отца вашего Небесного.",
                "Библия, Матфея 5:16",
            ),
            ThemedQuote(
                "bible",
                "А надеющиеся на Господа обновятся в силе: поднимут крылья, как орлы, потекут - и не устанут, пойдут - и не утомятся.",
                "Библия, Исаия 40:31",
            ),
            ThemedQuote(
                "bible",
                "Пусть любовь и верность никогда не покидают тебя; навяжи их на шею, запиши их на скрижали сердца.",
                "Библия, Притчи 3:3",
                translation="nrp",
            ),
            ThemedQuote(
                "bible",
                "Не заботьтесь ни о чем, но во всем, с молитвой и просьбой, с благодарностью открывайте свои желания Богу.",
                "Библия, Филиппийцам 4:6",
                translation="nrp",
            ),
            ThemedQuote(
                "bible",
                "Прежде всего ищите Царства Божьего и Его праведности, и все это вам тоже будет дано.",
                "Библия, Матфея 6:33",
                translation="nrp",
            ),
            ThemedQuote(
                "bible",
                "Будь тверд и мужественен! Не бойся и не ужасайся, потому что с тобой Господь, твой Бог, куда бы ты ни пошел.",
                "Библия, Иисуса Навина 1:9",
                translation="nrp",
            ),
            ThemedQuote(
                "bible",
                "Мы знаем, что Бог во всем действует во благо тех, кто любит Его, кто призван согласно Его замыслу.",
                "Библия, Римлянам 8:28",
                translation="nrp",
            ),
            ThemedQuote("bible", "Господь - свет мой и спасение мое: кого мне бояться?", "Библия, Псалом 26:1"),
            ThemedQuote("bible", "Господь близок к сокрушенным сердцем и спасает смиренных духом.", "Библия, Псалом 33:19"),
            ThemedQuote("bible", "Надейся на Господа всем сердцем твоим и не полагайся на разум твой.", "Библия, Притчи 3:5"),
            ThemedQuote("bible", "Мир оставляю вам, мир Мой даю вам.", "Библия, Иоанна 14:27"),
            ThemedQuote("bible", "Любящим Бога все содействует ко благу.", "Библия, Римлянам 8:28"),
        ],
    },
    "en": {
        "family": [
            ThemedQuote("family", "All happy families are alike.", "Leo Tolstoy"),
            ThemedQuote("family", "The family is one of nature's masterpieces.", "George Santayana"),
            ThemedQuote("family", "If you want to change the world, go home and love your family.", "Mother Teresa"),
            ThemedQuote("family", "The only rock I know that stays steady is the family.", "Lee Iacocca"),
            ThemedQuote("family", "Family is the most important thing in the world.", "Princess Diana"),
            ThemedQuote("family", "Love begins at home, and it is not how much we do... but how much love we put in that action.", "Mother Teresa"),
            ThemedQuote("family", "In every conceivable manner, the family is link to our past, bridge to our future.", "Alex Haley"),
            ThemedQuote("family", "You don't choose your family. They are God's gift to you, as you are to them.", "Desmond Tutu"),
            ThemedQuote("family", "Families are the compass that guide us.", "Brad Henry"),
            ThemedQuote("family", "The only rock I know that stays steady, the only institution I know that works, is the family.", "Lee Iacocca"),
        ],
        "discipline": [
            ThemedQuote("discipline", "We are what we repeatedly do.", "Aristotle"),
            ThemedQuote("discipline", "Discipline is the bridge between goals and accomplishment.", "Jim Rohn"),
            ThemedQuote("discipline", "Discipline equals freedom.", "Jocko Willink"),
            ThemedQuote("discipline", "I fear not the man who has practiced 10,000 kicks once.", "Bruce Lee"),
            ThemedQuote("discipline", "No man is free who is not master of himself.", "Epictetus"),
            ThemedQuote("discipline", "We become what we repeatedly do.", "Stephen Covey"),
            ThemedQuote("discipline", "Discipline is the bridge between goals and accomplishment.", "Jim Rohn"),
            ThemedQuote("discipline", "No man is free who is not master of himself.", "Epictetus"),
            ThemedQuote("discipline", "Take care of your body. It's the only place you have to live.", "Jim Rohn"),
            ThemedQuote("discipline", "To do the same thing over and over again is not only boredom: it is to be controlled by rather than to control what you do.", "Heraclitus"),
        ],
        "health": [
            ThemedQuote("health", "Let food be thy medicine.", "Hippocrates"),
            ThemedQuote("health", "Health is not everything, but without health everything is nothing.", "Arthur Schopenhauer"),
            ThemedQuote("health", "Those who think they have no time for health will sooner or later have to find time for illness.", "Edward Stanley"),
            ThemedQuote("health", "Physical fitness is the first requisite of happiness.", "Joseph Pilates"),
            ThemedQuote("health", "The greatest wealth is health.", "Virgil"),
            ThemedQuote("health", "Take care of your body. It's the only place you have to live.", "Jim Rohn"),
            ThemedQuote("health", "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "Buddha"),
            ThemedQuote("health", "Your body hears everything your mind says.", "Naomi Judd"),
            ThemedQuote("health", "You need to listen to your body because your body is listening to you.", "Phil McGraw"),
            ThemedQuote("health", "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.", "Ralph Marston"),
        ],
        "children": [
            ThemedQuote("children", "The best way to make children good is to make them happy.", "Oscar Wilde"),
            ThemedQuote("children", "Never help a child with a task at which he feels he can succeed.", "Maria Montessori"),
            ThemedQuote("children", "There can be no keener revelation of a society's soul than the way it treats its children.", "Nelson Mandela"),
            ThemedQuote("children", "Young people need models, not critics.", "John Wooden"),
            ThemedQuote("children", "The greatest sign of success for a teacher... is to be able to say, 'The children are now working as if I did not exist.'", "Maria Montessori"),
            ThemedQuote("children", "There can be no keener revelation of a society's soul than the way it treats its children.", "Nelson Mandela"),
            ThemedQuote("children", "Young people need models, not critics.", "John Wooden"),
            ThemedQuote("children", "Nobody can do for little children what grandparents do.", "Alex Haley"),
        ],
        "leadership": [
            ThemedQuote("leadership", "Leadership is the capacity to translate vision into reality.", "Warren Bennis"),
            ThemedQuote("leadership", "A leader knows the way, goes the way, and shows the way.", "John C. Maxwell"),
            ThemedQuote("leadership", "Management is doing things right; leadership is doing the right things.", "Peter Drucker"),
            ThemedQuote("leadership", "Example is not the main thing in influencing others. It is the only thing.", "Albert Schweitzer"),
            ThemedQuote("leadership", "If your actions inspire others to dream more, you are a leader.", "John Quincy Adams"),
            ThemedQuote("leadership", "Leaders keep their eyes on the horizon, not just on the bottom line.", "Warren Bennis"),
            ThemedQuote("leadership", "The manager has his eye on the bottom line; the leader has his eye on the horizon.", "Warren Bennis"),
            ThemedQuote("leadership", "Leaders are people who do the right thing; managers are people who do things right.", "Warren Bennis"),
            ThemedQuote("leadership", "The manager accepts the status quo; the leader challenges it.", "Warren Bennis"),
            ThemedQuote("leadership", "Leadership is the capacity to translate vision into reality.", "Warren Bennis"),
        ],
        "bible": [
            ThemedQuote("bible", "Above all else, guard your heart.", "Bible, Proverbs 4:23"),
            ThemedQuote("bible", "Let us not become weary in doing good.", "Bible, Galatians 6:9"),
            ThemedQuote("bible", "I can do all things through Christ who strengthens me.", "Bible, Philippians 4:13"),
            ThemedQuote("bible", "Let your light shine before others.", "Bible, Matthew 5:16"),
            ThemedQuote("bible", "Those who hope in the Lord will renew their strength.", "Bible, Isaiah 40:31"),
            ThemedQuote("bible", "The Lord is my light and my salvation; whom shall I fear?", "Bible, Psalm 27:1"),
            ThemedQuote("bible", "The Lord is close to the brokenhearted.", "Bible, Psalm 34:18"),
            ThemedQuote("bible", "Trust in the Lord with all your heart.", "Bible, Proverbs 3:5"),
            ThemedQuote("bible", "Peace I leave with you; my peace I give you.", "Bible, John 14:27"),
            ThemedQuote("bible", "In all things God works for the good of those who love him.", "Bible, Romans 8:28"),
        ],
    },
}

THEMED_QUOTES: dict[str, dict[str, list[ThemedQuote]]] = BASE_THEMED_QUOTES
